-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 16:28:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema equim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema equim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equim` DEFAULT CHARACTER SET utf8 ;
USE `equim` ;

-- -----------------------------------------------------
-- Table `equim`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equim`.`users` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `emaill` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emaill_UNIQUE` (`emaill` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equim`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equim`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equim`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equim`.`products` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT NULL,
  `precio` INT(11) NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_products_categories1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `equim`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equim`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equim`.`cart` (
  `idcart` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `fk_cart_users1_idx` (`id_usuario` ASC),
  INDEX `fk_cart_products1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `equim`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `equim`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
